### ISSUE TITLE
run a KG2.7.2 build

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#104] opened 2021-08-04 22:25 UTC
- [x] make sure issue95 branch Travis CI test-suite passes
- [x] create a `r5a.8xlarge` instance `kg2build.rtx.ai` for the build
- [x] clone the RTX-KG2 repo into the instance but use the `issue95` branch
- [x] update the `README.md` in the `issue95` branch to reflect the new flags added for Snakemake
- [x] download TSV file for the infores Google Sheet and copy it into the instance
- [x] run the infores verification script on the TSV file in the instance
- [x] update code in issue95 branch to load SemMedDB version 43 (cross-reference #87)
- [x] run a "all -F" build with the "-n" flag
- [x] check the output of the "-n" run to make sure every target will be run
- [x] run a "all -F" build without the "-n" flag (this should take approximately 48 hours)
- [x] verify that the new build is in fact versioned 2.7.2
- [x] check report file `kg2-simplified-report.json`; compare against previous `kg2-simplified-report.json` to identify any major changes
- [x] install the new KG2 TSV files into Neo4j on `kg2endpoint4.rtx.ai`
- [x] create a DNS CNAME record for `kg2-7-2.rtx.ai` pointing to `kg2endpoint4.rtx.ai`
- [x] document the build in `kg2-versions.md` in the `issue95` branch
- [x] merge `issue95` branch into `master` branch (carefully audit any commits upstream to see if they change anything about the build process??)
- [x] update L122-123 in `build-kg2-snakemake.sh` (see https://github.com/RTXteam/RTX-KG2/issues/104#issuecomment-893104520)
- [x] tag the RTX-KG2 master branch and do a GitHub "release" with version `KG2.7.2`
- [x] build Node Synonymizer against KG2.7.2-neo4j
- [x] build `KG2.7.2c`
- [x] validate `KG2.7.2c`
- [x] #130
- [x] push `kg2c_lite_2.7.2.json.gz` to [NCATS repo](https://github.com/ncats/translator-lfs-artifacts/tree/main/files)
- [x] coordinate with Amy
- [ ] coordinate with Eric, Finn, and Chunyu for handoff

**Comment by saramsey** [comment] 2021-08-04 22:25
See also instructions in this Google Sheet:
https://docs.google.com/presentation/d/1ezj-da1jrCshtfN-GuQXVSmwhsMFfRUsmbMhEOsD3eY/edit#slide=id.ge4812a41a4_0_130

**Comment by ericawood** [comment] 2021-08-04 22:28
Here are the available `build-kg2-snakemake.sh` options: (Format: `flag` [slots it works in, starting at 1])

- `test` [1]: This flag initiates a test build, which creates a much smaller graph (which can be used for debugging).
- `all` [1]: This flag initiates a full build, which includes the extraction scripts. (Omitting this flag initiates a partial build, which requires that the output of all of the extraction scripts already exits).
- `alltest` [1]: This flag initaites a test build that includes extracting SemMedDB's test edges file. Before you can run a build with the `test` flag, you **must** run a build on that same instance with the `alltest` flag. (SemMedDB's conversion requires a test version of the input). 
- `-n` [1-4]: This flag initiates a dryrun of the build, outputting to a different file (with the `-n` flag in the file name). This is good to do before running a real build to make sure that the scripts you want to run will be included and the scripts you don't won't.
- `nodes` [1-4]: This flag generates a version of `kg2-simplified.json` that is exclusively the nodes (for debugging purposes). It takes extra time, so it should only be included when necessary. Also, if you plan to use it, familiarize yourself with the `nodes` related code in `build-kg2-snakemake.sh`.
- `-R_*` [1-3]: This is our version of Snakemake's `-R` flag. However, rather than using it in the form `-R Rule` (ex. `-R Merge`), we add an underscore between them (`-R_Rule`) to simplify the command line options decoding process. This forces a rerun of all the rules that provide an input to the rule listed. For example, if you wanted to rerun all of the conversion rules, you might use `-R_Merge`. This one is more tricky to use and I'd recommend both reading up on what Snakemake says about it and doing dryruns until you get the effect you are looking for.
- `-F` [1-3]: This flag forces a rerun of all of the rules that lead up to the first rule in the Snakefile, which is `Finish` and depends on all of the rules. Thus, this will rebuild everything.
- `graphic` [1-3]: This flag generates the PNG diagram of the Snakemake workflow
- `travisci` [3-5]: This flag should only be used in the `.travis.yml` file (for usage on a Travis CI instance). It ensures that the commands are configured to run on a Travis CI instance (where we can't use a virtualenv).

Examples:

- Bad: `bash -x build-kg2-snakemake.sh -n test` (`test` flag **must** be in position 1)
- Good: `bash -x build-kg2-snakemake.sh all -F nodes -n travisci` (every flag is in an allowable position for it)

**Comment by saramsey** [comment] 2021-08-04 23:53
Here is the infores catalog file:

[infores-catalog.tsv.zip](https://github.com/RTXteam/RTX-KG2/files/6934989/infores-catalog.tsv.zip)

**Comment by saramsey** [comment] 2021-08-04 23:55
For step 5 above, I named the file `infores-catalog.tsv` and copied it into `~/kg2-build/` in the instance:

**Comment by saramsey** [comment] 2021-08-04 23:58
Validating the `infores-catalog.tsv` by running (as user `ubuntu` and in the `kg2-build` directory):

```
source ~/kg2-venv/bin/activate
python3 ~/kg2-code/validate_provided_by_to_infores_map_yaml.py \
  ~/kg2-code/kg2-provided-by-curie-to-infores-curie.yaml \
  ./infores-catalog.tsv

It ran without producing any output (@ericawood confirmed via Zoom that this means that it ran without finding any errors).

**Comment by saramsey** [comment] 2021-08-05 00:00
now resuming the regular build instructions in the `issue95` branch under "Option 1" at step (7)

**Comment by saramsey** [comment] 2021-08-05 00:01
Saving the `build-kg2-snakemake-n.log` file here:
[build-kg2-snakemake-n.log.zip](https://github.com/RTXteam/RTX-KG2/files/6935023/build-kg2-snakemake-n.log.zip)

**Comment by saramsey** [comment] 2021-08-05 00:02
The `build-kg2-snakemake-n.log` file ends with:
```
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
+ date
Thu Aug  5 00:00:40 UTC 2021
+ echo '================ script finished ============================'
================ script finished ============================
```
so looks like normal output (?). Proceeding....

**Comment by saramsey** [comment] 2021-08-05 00:06
OK, before running step (8), I forgot to update `extract-semmeddb.sh` to pull version 43 of SemMedDB. Fixing that now.

**Comment by saramsey** [comment] 2021-08-05 00:08
Running this code in the instance, to update the code to the tip if the `issue95` branch, before running step (8) of the instructions:
```
cd ~/kg2-code && git pull
```

**Comment by ericawood** [comment] 2021-08-05 00:43
> The `build-kg2-snakemake-n.log` file ends with:
> 
> ```
> This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
> + date
> Thu Aug  5 00:00:40 UTC 2021
> + echo '================ script finished ============================'
> ================ script finished ============================
> ```
> 
> so looks like normal output (?). Proceeding with step (8) in the Option 1 instructions in the `README.md` in the `issue95` branch....

Going forward, I would recommend checking that the expected number of rules ran as well. If you are doing a partial build, you should also verify that the rules you want are there and the rules you don't aren't.

**Comment by ericawood** [comment] 2021-08-05 02:02
If this build goes smoothly and you opt to merge the branch into master, please remember to edit these lines:
https://github.com/RTXteam/RTX-KG2/blob/2d0e139c3b8a4736d0e2579e49b281d2377647b6/build-kg2-snakemake.sh#L122-L123
to say `origin/master` instead. (Essentially, these lines ensure that, if you want the KG2 nodes file to be generates, the potentially sed-ed files (see lines above) aren't used.)

**Comment by saramsey** [comment] 2021-08-05 14:35
Build died at 0750 UTC

<img width="211" alt="Screen Shot 2021-08-05 at 7 34 00 AM" src="https://user-images.githubusercontent.com/5562107/128368314-aa6ec811-f7eb-4891-a772-1e1d1b5cfb99.png">

shutting down the instance for now. I will investigate as soon as I get to work.

**Comment by saramsey** [comment] 2021-08-05 16:24
OK, in `/home/ubuntu/kg2-build/build-kg2-snakemake.log`, I am seeing the following error message:
```
Error in rule UniChem:
    jobid: 33
    output: /home/ubuntu/kg2-build/unichem/unichem-mappings.tsv
    log: /home/ubuntu/kg2-build/extract-unichem.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/extract-unichem.sh /home/ubuntu/kg2-build/unichem/unichem-mappings.tsv > /home/ubuntu/kg2-build/extract-unichem.log 2>&1
        (exited with non-zero exit code)
```

**Comment by saramsey** [comment] 2021-08-05 16:25
Archiving `build-kg2-snakemake.log` here:

[build-kg2-snakemake.log.zip](https://github.com/RTXteam/RTX-KG2/files/6940190/build-kg2-snakemake.log.zip)

**Comment by saramsey** [comment] 2021-08-05 16:26
Checking the last line of `/home/ubuntu/kg2-build/extract-unichem.log`, I am seeing:
```
+ curl -s -L -f ftp://ftp.ebi.ac.uk/pub/databases/chembl/UniChem/data/oracleDumps/UDRI371/UC_XREF.txt.gz
```

**Comment by saramsey** [comment] 2021-08-05 16:29
It appears that the `UDRI371` directory is no longer present on the EBI FTP server, as shown here:
<img width="503" alt="Screen Shot 2021-08-05 at 9 28 49 AM" src="https://user-images.githubusercontent.com/5562107/128386680-ab00b074-25d9-48b3-a78f-7e588577b146.png">

**Comment by saramsey** [comment] 2021-08-05 16:37
> > The `build-kg2-snakemake-n.log` file ends with:
> > ```
> > This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.
> > + date
> > Thu Aug  5 00:00:40 UTC 2021
> > + echo '================ script finished ============================'
> > ================ script finished ============================
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so looks like normal output (?). Proceeding with step (8) in the Option 1 instructions in the `README.md` in the `issue95` branch....
> 
> Going forward, I would recommend checking that the expected number of rules ran as well. If you are doing a partial build, you should also verify that the rules you want are there and the rules you don't aren't.

OK, thanks, I have noted this in the `README.md`

**Comment by saramsey** [comment] 2021-08-05 17:25
<img width="295" alt="Screen Shot 2021-08-05 at 10 24 52 AM" src="https://user-images.githubusercontent.com/5562107/128394216-4e65139d-673e-48d1-95e0-461b4454f7e3.png">

**Comment by saramsey** [comment] 2021-08-05 17:31
Resuming the build:
```
bash -x ~/kg2-code/build-kg2-snakemake.sh all
```

**Comment by saramsey** [comment] 2021-08-05 17:31
Verified that the bugfix works, using:
```
/home/ubuntu/kg2-venv/bin/snakemake --snakefile /home/ubuntu/kg2-code/Snakefile -R --until UniChem
```

**Comment by saramsey** [comment] 2021-08-05 17:32
Resuming the build using:
```
bash -x ~/kg2-code/build-kg2-snakemake.sh all
```

**Comment by saramsey** [comment] 2021-08-05 17:56
Seeing an error in the `~/kg2-build/build-kg2-snakemake.log` file:
```
[Thu Aug  5 17:30:23 2021]
Error in rule KEGG:
    jobid: 47
    output: /home/ubuntu/kg2-build/kegg.json
    log: /home/ubuntu/kg2-build/extract-kegg.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/extract-kegg.sh /home/ubuntu/kg2-build/kegg.json > /home/ubuntu/kg2-build/extract-kegg.l
og 2>&1
        (exited with non-zero exit code)
```

**Comment by saramsey** [comment] 2021-08-05 18:28
Seeing an error in `~/kg2-build/build-kg2-snakemake.log`:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py", line 279, in <module>
    version_number = json_data['version'][0]['version']
KeyError: 'version'
[Thu Aug  5 17:30:27 2021]
Error in rule DrugCentral_Conversion:
    jobid: 23
    output: /home/ubuntu/kg2-build/kg2-drugcentral.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py  /home/ubuntu/k
g2-build/drugcentral/drugcentral_psql_json.json /home/ubuntu/kg2-build/kg2-drugcentral.json
        (exited with non-zero exit code)
```
tracking the fix for this issue in #108

**Comment by saramsey** [comment] 2021-08-05 19:56
Seeing an error in the `DrugCentral_Conversion` rule in `~/kg2-build/build-kg2-snakemake.log` file:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py", line 279, in <module>
    version_number = json_data['version'][0]['version']
KeyError: 'version'
[Thu Aug  5 17:30:27 2021]
Error in rule DrugCentral_Conversion:
    jobid: 23
    output: /home/ubuntu/kg2-build/kg2-drugcentral.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py  /home/ubuntu/kg2-build/drugcentral/drugcentral_psql_json.json /home/ubuntu/kg2-build/kg2-drugcentral.json
        (exited with non-zero exit code)
```

**Comment by saramsey** [comment] 2021-08-05 20:17
Error in task `Reactome_Conversion`:
```
[Thu Aug  5 17:31:29 2021]
Error in rule Reactome_Conversion:
    jobid: 20
    output: /home/ubuntu/kg2-build/kg2-reactome.json
    log: /home/ubuntu/kg2-build/reactome-mysql-to-kg-json.log (check log file(s) for error message)
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/reactome_mysql_to_kg_json.py  /home/ubuntu/kg2-build/mysql-config.conf reactome /home/ubuntu/kg2-build/kg2-reactome.json > /home/ubuntu/kg2-build/reactome-mysql-to-kg-json.log 2>&1
        (exited with non-zero exit code)
```
tracking this as #110

**Comment by saramsey** [comment] 2021-08-05 20:22
Error in task `Ensembl_Conversion`:
```
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 180, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 137, in make_kg2_graph
    name = transcript['name']
KeyError: 'name'
[Thu Aug  5 17:32:19 2021]
Error in rule Ensembl_Conversion:
    jobid: 11
    output: /home/ubuntu/kg2-build/kg2-ensembl.json
    shell:
        /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/ensembl_json_to_kg_json.py  /home/ubuntu/kg2-build/ensembl/ensembl_genes_homo_sapiens.json /home/ubuntu/kg2-build/kg2-ensembl.json
        (exited with non-zero exit code)
```
tracking this as #111

**Comment by saramsey** [comment] 2021-08-05 22:59
Ran this test on `buildkg2.rtx.ai`:
```
bash -x /home/ubuntu/kg2-code/extract-kegg.sh /home/ubuntu/kg2-build/kegg.json > /home/ubuntu/kg2-build/extract-kegg.log 2>&1
```
and got this error:
```
+ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/query_kegg.py /home/ubuntu/kg2-build/kegg.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/cachecontrol/caches/file_cache.py", line 72, in __init__
    from lockfile import LockFile
ModuleNotFoundError: No module named 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/query_kegg.py", line 124, in <module>
    kg2_util.save_json(run_queries(), args.outputFile, True)
  File "/home/ubuntu/kg2-code/query_kegg.py", line 90, in run_queries
    for results in send_query(query).split('\n'):
  File "/home/ubuntu/kg2-code/query_kegg.py", line 37, in send_query
    requests = CacheControlHelper()
  File "/home/ubuntu/RTX-KG2/cache_control_helper.py", line 32, in __init__
    self.sess = CacheControl(requests.session(), heuristic=CustomHeuristic(days=30), cache=FileCache('.web_cache'))
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/cachecontrol/caches/file_cache.py", line 82, in __init__
    raise ImportError(notice)
ImportError:
NOTE: In order to use the FileCache you must have
lockfile installed. You can install it via pip:
  pip install lockfile
```

**Comment by saramsey** [comment] 2021-08-05 22:59
On `kg2lindsey.rtx.ai`, it looks like the installed version of `lockfile` is 0.12.2:
```
(kg2-venv) ubuntu@ip-172-31-59-26:~$ pip3 freeze | grep lockfile
lockfile==0.12.2
```

**Comment by saramsey** [comment] 2021-08-05 23:06
Rerunning the KEGG test on `buildkg2.rtx.ai`:
```
bash -x /home/ubuntu/kg2-code/extract-kegg.sh /home/ubuntu/kg2-build/kegg.json > /home/ubuntu/kg2-build/extract-kegg.log 2>&1
```

**Comment by saramsey** [comment] 2021-08-05 23:17
Another issue in the `Ensembl-Conversion` rule:
```
ubuntu@ip-172-31-63-157:~/kg2-code$ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/ensembl_json_to_kg_json.py  /home/ubuntu/kg2-build/ensembl/ensembl_genes_homo_sapiens.json /home/ubuntu/kg2-build/kg2-ensembl.json
Traceback (most recent call last):
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 180, in <module>
    graph = make_kg2_graph(input_file_name, test_mode)
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 99, in make_kg2_graph
    go_xrefs = add_prefixes_to_curie_list(gene_dict.get('GO', ''), kg2_util.CURIE_PREFIX_GO)
  File "/home/ubuntu/kg2-code/ensembl_json_to_kg_json.py", line 60, in add_prefixes_to_curie_list
    curie = curie['term'] + ' ' + curie['evidence'][0]
TypeError: can only concatenate str (not "NoneType") to str
```
Tracking as #112

**Comment by saramsey** [comment] 2021-08-05 23:51
OK, I believe the `Ensembl-Conversion` bug was fixed in #112. Rerunning manually that rule on `buildkg2.rtx.ai`:
```
/home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/ensembl_json_to_kg_json.py  /home/ubuntu/kg2-build/ensembl/ensembl_genes_homo_sapiens.json /home/ubuntu/kg2-build/kg2-ensembl.json
```

**Comment by saramsey** [comment] 2021-08-05 23:56
OK, I manually ran the extract-drugcentral rule and it produced an 83M file `~/kg2-build/kg2-drugcentral.json`:
```
ubuntu@ip-172-31-63-157:~/kg2-build$ /home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/drugcentral_json_to_kg_json.py  /home/ubuntu/kg2-build/drugcentral/drugcentral_psql_json.json /home/ubuntu/kg2-build/kg2-drugcentral.json
ubuntu@ip-172-31-63-157:~/kg2-build$ ls -alh drugcentral/
total 1.1G
drwxrwxr-x  2 ubuntu ubuntu 4.0K Aug  5 00:16 .
drwxrwxr-x 16 ubuntu ubuntu  12K Aug  5 23:54 ..
-rw-rw-r--  1 ubuntu ubuntu 998M Aug  5 00:13 drugcentral.sql.gz
-rw-rw-r--  1 ubuntu ubuntu 124M Aug  5 00:17 drugcentral_psql_json.json
-rw-rw-r--  1 ubuntu ubuntu   27 Aug  5 00:17 psql_dump_file.txt
ubuntu@ip-172-31-63-157:~/kg2-build$ ls -alh kg2-drugcentral.json
-rw------- 1 ubuntu ubuntu 83M Aug  5 23:54 kg2-drugcentral.json
```

**Comment by saramsey** [comment] 2021-08-05 23:57
On `buildkg2.rtx.ai`, I am manually running the Reactome conversion:
```
/home/ubuntu/kg2-venv/bin/python3 -u /home/ubuntu/kg2-code/reactome_mysql_to_kg_json.py  /home/ubuntu/kg2-build/mysql-config.conf reactome /home/ubuntu/kg2-build/kg2-reactome.json > /home/ubuntu/kg2-build/reactome-mysql-to-kg-json.log 2>&1
```

**Comment by saramsey** [comment] 2021-08-06 00:07
Current process table on `buildkg2.rtx.ai`:
![Screen Shot 2021-08-05 at 5 07 07 PM](https://user-images.githubusercontent.com/5562107/128436652-ad237a28-c2d1-4119-b0ee-a02a622f2a1f.png)

**Comment by saramsey** [comment] 2021-08-06 00:12
Note, I am not presently testing the fix for #108 since the `DrugCentral_Conversion` rule seemed to complete despite those SQL errors. So issue #108 will remain marked "verify in next build" for now.

**Comment by saramsey** [comment] 2021-08-06 19:35
Looks like `multi_ont_to_json_kg.py` exited with an error:
```
Error in rule Ontologies_and_TTL:
    jobid: 7
    output: /home/ubuntu/kg2-build/kg2-ont.json
    log: /home/ubuntu/kg2-build/build-multi-ont-kg.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/build-multi-ont-kg.sh /home/ubuntu/kg2-build/umls_cuis.tsv /home/ubuntu/kg2-build/kg2-ont.json  > /home/ubuntu/kg2-build/build-multi-ont-kg.log 2>&1
        (exited with non-zero exit code)
```

**Comment by saramsey** [comment] 2021-08-06 19:40
Here is the complete `build-kg2-snakemake.log` for the build that resulted in the errors reported above:
[build-kg2-snakemake.log.zip](https://github.com/RTXteam/RTX-KG2/files/6947659/build-kg2-snakemake.log.zip)

**Comment by saramsey** [comment] 2021-08-06 19:50
Seeing a bunch of warnings about AraPort in multi_ont_to_kg_json.py, recorded in #114

**Comment by saramsey** [comment] 2021-08-06 19:53
Restarting the build now, on `buildkg2.rtx.ai`, by running (as user `ubuntu`):
```
cd 
bash -x ~/kg2-build/build-kg2-snakemake.sh 
```

**Comment by saramsey** [comment] 2021-08-06 19:56
Just inspected the build plan `build-kg2-snakemake-n.log`. The plan looks correct:
```
Job counts:
        count   jobs
        1       Finish
        1       KEGG_Conversion
        1       Merge
        1       Ontologies_and_TTL
        1       Simplify
        1       Simplify_Stats
        1       Slim
        1       Stats
        1       TSV
        9
```
Here is the "-n" plan file:
[build-kg2-snakemake-n.log.zip](https://github.com/RTXteam/RTX-KG2/files/6947722/build-kg2-snakemake-n.log.zip)

**Comment by saramsey** [comment] 2021-08-06 19:57
Now running `build-kg2-snakemake.sh`, as user `ubuntu` in `/home/ubuntu` in a screen session on `buildkg2.rtx.ai`:
```
cd
bash -x ~/kg2-code/build-kg2-snakemake.sh
```

**Comment by saramsey** [comment] 2021-08-07 15:59
Error in rule `Simplify`:
```
Error in rule Simplify:
    jobid: 3
    output: /home/ubuntu/kg2-build/kg2-simplified.json
    log: /home/ubuntu/kg2-build/filter_kg_and_remap_predicates.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/run-simplify.sh /home/ubuntu/kg2-build/kg2.json /home/ubuntu/kg2-build/kg2-simplified.json /home/ubuntu/kg2-build/kg2-version.txt  > /home/ubuntu/kg2-build/filter_kg_and_remap_predicates.log 2>&1
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/.snakemake/log/2021-08-06T195800.503566.snakemake.log
~
~
~
```

**Comment by saramsey** [comment] 2021-08-08 17:41
restarting the build by running (as user `ubuntu` in a `screen` session on system `buildkg2.rtx.ai`:
```
cd
bash -x ~/kg2-code/build-kg2-snakemake.sh
```

**Comment by saramsey** [comment] 2021-08-09 16:48
build terminated, error (from the `build-kg2-snakemake.log` file) is shown here:
```
[Sun Aug  8 20:10:46 2021]
Error in rule Simplify:
    jobid: 3
    output: /home/ubuntu/kg2-build/kg2-simplified.json
    log: /home/ubuntu/kg2-build/filter_kg_and_remap_predicates.log (check log file(s) for error message)
    shell:
        bash -x /home/ubuntu/kg2-code/run-simplify.sh /home/ubuntu/kg2-build/kg2.json /home/ubuntu/kg2-build/kg2-simplified.json /home/ubuntu/kg2-build/kg2-version.txt  > /home/ubuntu/kg2-build/filter_kg_and_remap_predicates.log 2>&1
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/ubuntu/.snakemake/log/2021-08-08T174120.823762.snakemake.log
```
complete logfile here:
[build-kg2-snakemake.log.zip](https://github.com/RTXteam/RTX-KG2/files/6956061/build-kg2-snakemake.log.zip)

Issue reported in detail in #116

**Comment by saramsey** [comment] 2021-08-09 17:18
resuming the KG2.7.2 build on `buildkg2.rtx.ai`

**Comment by saramsey** [comment] 2021-08-09 20:52
OK, `filter_kg_and_remap_predicates.py` has completed on `buildkg2.rtx.ai`. Now it is running `slim_kg2.py`.

**Comment by saramsey** [comment] 2021-08-09 20:52
Confirming the correct KG2 version number in this build:

![Screen Shot 2021-08-09 at 1 52 24 PM](https://user-images.githubusercontent.com/5562107/128772898-2ee8619f-ddb9-4d2b-a88b-2ee5d10ea3c1.png)

**Comment by saramsey** [comment] 2021-08-09 22:39
At 21:58 UTC on 8/9/2021, an error occurred in the rule `TSV` for the KG2.7.2 build on `buildkg2.rtx.ai` (see #117 for details).

**Comment by saramsey** [comment] 2021-08-10 17:38
The build process seems to have hung at approximately 2025 UTC on Aug. 9, 2021. See #118.

**Comment by saramsey** [comment] 2021-08-10 17:38
Now that #118 is (hopefully) fixed, resuming the build on `buildkg2.rtx.ai`....

**Comment by saramsey** [comment] 2021-08-10 17:41
Build KG2.7.2 appears to have "completed" (as in, the `build-kg2-snakemake.sh` script completed) on `buildkg2.rtx.ai`:
```
Tue Aug 10 17:39:35 UTC 2021
+ echo '================ script finished ============================'
================ script finished ============================
```

**Comment by saramsey** [comment] 2021-08-10 17:57
Just created an `r5a.2xlarge` instance in `us-west-2` and assigned it hostname `kg2endpoint4.rtx.ai`, to host the Neo4j for KG2.7.2.

**Comment by saramsey** [comment] 2021-08-10 17:57
Running the `setup-kg2-neo4j.sh` script in instance `kg2endpoint4.rtx.ai`, we get an error:
```
Collecting pandas (from ontobio==1.10.1->-r /home/ubuntu/kg2-code/requirements-kg2-neo4j.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/12/01/360d7f444f910ae16496c07e3f003cb8c641b4ca6c033408a4469a904df3/pandas-1.3.1.tar.gz (4.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gtghlz5t/pandas/setup.py", line 18, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gtghlz5t/pandas/
```

**Comment by saramsey** [comment] 2021-08-10 18:11
OK, issue #119 is now fixed, resuming the build on `kg2endpoint4.rtx.ai`....

**Comment by saramsey** [comment] 2021-08-10 18:27
The usual issue #29 arose again. Attempted a fix (see #29 for details and the commits) but I am not optimistic. Used the usual workaround of setting the Neo4j password using my web browser. Had to restart neo4j for it to work; fixed that as well.

**Comment by saramsey** [comment] 2021-08-10 19:29
OK, `tsv-to-neo4j.sh` completed:
```

IMPORT DONE in 10m 47s 952ms.
Imported:
  10237436 nodes
  54036959 relationships
  774866172 properties
Peak memory usage: 1.16 GB
Tue Aug 10 18:45:33 UTC 2021
Sleeping for 1 minute, please do not SIGINT....
/home/ubuntu/kg2-build/RTXConfiguration-config.json
NOTE: If you are running create_indexes_constraints.py standalone and not via tsv-to-neo4j.sh, please make sure to re-set the read-only status of the Neo4j database to TRUE
Tue Aug 10 18:47:34 UTC 2021
Sleeping for 5 minutes, please do not SIGINT....
/home/ubuntu/kg2-venv/lib/python3.7/site-packages/scipy/__init__.py:149: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.16.3
  UserWarning)
Tue Aug 10 18:55:22 UTC 2021
================ script finished ============================

**Comment by acevedol** [comment] 2021-08-10 23:31
The files kg2-simplified-report.json show an increase in actively_involved_in edges from 3309 to 19781, which looks like the biggest increase. 
2.7.2 has predicate curies, "catalyzes", "examples", "local names", "transcribed from", and "translates to", that I didn't see in 2.7.1
2.7.1 had predicate curies, "has_gene_product" and "part of", that I don't see in 2.7.2
The two files appear overall very similar, nothing stands out as glaringly wrong

**Comment by acevedol** [comment] 2021-08-11 23:09
Merged issue 95 branch to master branch. Updated L122 and 123 in build-kg2-snakemake.sh to point to master branch

**Comment by saramsey** [comment] 2021-08-12 03:36
Hi @acevedol are you sure the merge was completed?  Looking at `kg2-versions.md`, it looks like the version of that file in the `issue95` branch is newer than the one in the `master` branch....

**Comment by saramsey** [comment] 2021-08-12 04:09
Hi @acevedol  it looks like there is a PR for the merge, is that right?  But some tests are failing?  Can you let me know what I should do?  Should I merge the PR?  Your comment earlier today led me to believe it was already merged, that is what gives me pause. Thanks in advance for clarifying.

<img width="890" alt="Screen Shot 2021-08-11 at 9 07 39 PM" src="https://user-images.githubusercontent.com/5562107/129136998-216e60c7-a91f-4708-820b-f02660983416.png">

**Comment by saramsey** [comment] 2021-08-12 23:52
Hi @amykglen does the checklist at the top of this issue look sane?

**Comment by amykglen** [comment] 2021-08-13 01:48
yes, looks sane to me!

**Comment by saramsey** [comment] 2021-08-16 16:48
Commit 8e12192 is to fix the issue on L122-132 of `build-kg2-snakemake.sh` (changing `issue95` to `master`).

**Comment by acevedol** [comment] 2021-08-16 16:53
Starting synonymizer build with configuration settings 
![Screen Shot 2021-08-16 at 9 47 09 AM](https://user-images.githubusercontent.com/59181061/129599810-c31ddea4-3d68-4105-bda3-95d67a6edd2f.png)

**Comment by acevedol** [comment] 2021-08-16 17:29
Running into KeyError 
![Screen Shot 2021-08-16 at 9 51 50 AM](https://user-images.githubusercontent.com/59181061/129604917-2ed8b725-9dcb-430f-a744-f9e4d4682687.png)

**Comment by amykglen** [comment] 2021-08-16 17:40
I think that's resolved now @acevedol (there was an issue where changes in the master copy of `configv2.json` had been overwritten, but I corrected that). I confirmed with a test build on `buildkg2c.rtx.ai`.

**Comment by acevedol** [comment] 2021-08-16 17:44
Thank you, Amy! The synonymizer build now appears to be running

**Comment by saramsey** [comment] 2021-08-16 20:22
> Thank you, Amy! The synonymizer build now appears to be running

WOO HOO!  Nice.

**Comment by acevedol** [comment] 2021-08-16 22:36
Synonymizer build finished, but threw an error about the generated sqlite file
I am investigating what happened
![Screen Shot 2021-08-16 at 3 34 43 PM](https://user-images.githubusercontent.com/59181061/129637582-b99e422c-46d5-48a1-a8ed-64e7cb84fb50.png)

**Comment by amykglen** [comment] 2021-08-16 22:54
fixed in `master` (the newly built synonymizer is given the name in `configv2.json` automatically now apparently, so that command was no longer needed)

**Comment by acevedol** [comment] 2021-08-16 22:59
Conferred with Amy and used `bash -x upload-synonymizer-artifacts.sh /data/orangeboard/databases/KG2.7.2 node_synonymizer_v1.0_KG2.7.2.sqlite` to continue build

Looks like all the expected files are in the KG2.7.2 directory now

![Screen Shot 2021-08-16 at 3 57 24 PM](https://user-images.githubusercontent.com/59181061/129639321-5ca3f414-eeae-46ac-84b6-864808b528a0.png)

**Comment by acevedol** [comment] 2021-08-18 17:55
It looks like the KG2C files made it into their directory in arax.ncats.io and have grown from their versions in KG2.7.1
![Screen Shot 2021-08-18 at 10 32 17 AM](https://user-images.githubusercontent.com/59181061/129945165-6b3b6d6f-acc3-4adc-a030-ce971d9c3f66.png)

**Comment by acevedol** [comment] 2021-08-18 17:56
Loading KG2C into Neo4J on kg2canonicalized2.rtx.ai

**Comment by acevedol** [comment] 2021-08-18 18:20
updated CName record for kg2canonicalized2.rtx.ai to kg2-7-2c.rtx.ai

**Comment by acevedol** [comment] 2021-08-18 23:51
The version of kg2-simplified.json.gz in the S3 bucket is from January, which doesn't seem right.

**Comment by acevedol** [comment] 2021-08-21 00:17
Uploading kg2-simplified2.7.2.json.xz failed. The file size (4.84 GiB/5.19GB) is still too large. Need to look into other compression methods. 

![Screen Shot 2021-08-20 at 5 12 59 PM](https://user-images.githubusercontent.com/59181061/130304155-fd929ade-17bf-46c3-8bb4-dc071338676a.png)

**Comment by saramsey** [comment] 2021-08-30 23:18
Hi Lili, do we know how much we would need to compress the file, in order to enable us to push it to the NCATS GitHub LFS repo?

**Comment by saramsey** [comment] 2021-09-02 14:09
Confirmed with @acevedol that she has managed to compress `kg2-simplified.json` (using `xz -9` I think?) to small enough that it could be pushed to the `ncats/translator-lfs-artifacts` repo; in this case to the `kg2.7.2` branch of that repo).

**Closed** 2021-09-28 17:18 UTC
