### ISSUE TITLE
OMIM edge mapped to wrong Biolink predicate (subclass_of)

### ISSUE THREAD

**Issue by amykglen** [RTXteam/RTX-KG2#267] opened 2023-03-31 16:34 UTC
in this issue (part of the TAQA working group), Sierra reported that KG2 seems to incorrectly think GERD is a subclass of X-linked Opitz G/BBB syndrome:

https://github.com/NCATSTranslator/Feedback/issues/107

tracing the issue, it looks like the problem edge comes from OMIM:
```
match p=(n {id:"OMIM:MTHU002522"})-[`biolink:subclass_of`]->(m {id:"OMIM:300000"}) return p limit 50
```
![Screen Shot 2023-03-31 at 9 30 34 AM](https://user-images.githubusercontent.com/49423686/229178207-055a83c3-757f-4e06-b296-3b618a287d95.png)
(note: I ran this query on KG2.8.1)

it appears that the OMIM predicate `OMIM:has_manifestation` is being mapped to `biolink:subclass_of` (at least for the `core_predicate`... which I guess must be the property KG2c loads into `predicate`?) 
**I think the correct Biolink predicate is probably `biolink:has_manifestation`?** (or I guess `biolink:manifestation_of`, with the edge direction flipped...)

this is a fairly high-impact bug since the KG2 KP relies on `subclass_of` edges for concept reasoning (in all queries)

**Comment by amykglen** [comment] 2023-03-31 16:46
FYI, it appears there are around 100k edges that have a `predicate_label` of `has_manifestation` but a `core_predicate` of `biolink:subclass_of`:
```
match p=(n)-[e]->(m) where e.predicate_label="has_manifestation" and e.core_predicate="biolink:subclass_of" return e.knowledge_source, count(e) order by count(e) desc
```
e.knowledge_source | count(e)
-- | --
["infores:omim"] | 121749

**Comment by saramsey** [comment] 2023-06-12 18:26
Fixed. 

<img width="1082" alt="Screen Shot 2023-06-12 at 11 25 44 AM" src="https://github.com/RTXteam/RTX-KG2/assets/5562107/60a6e0a4-25ed-48b8-aafe-bd9754b7ce1f">

**Comment by saramsey** [comment] 2023-08-01 23:40
Hmm, in KG2.8.4pre, we still have the inverted predicate, which is not fixed. 
On Neo4j endpoint `kg2endpoint-kg2-8-4.rtx.ai:7474`, the Cypher query:
```
match (n {id: 'OMIM:MTHU002522'})<-[r]-(m {id: 'OMIM:300000'}) return r;
```
returns an edge with predicate `biolink:superclass_of`:
```
{
  "predicate": "biolink:superclass_of",
  "domain_range_exclusion": "False",
  "negated": "False",
  "primary_knowledge_source": "infores:omim",
  "relation_label": "has_manifestation",
  "publications_info": "{}",
  "subject": "OMIM:300000",
  "source_predicate": "OMIM:has_manifestation",
  "predicate_label": "has_manifestation",
  "id": "OMIM:300000---OMIM:has_manifestation---None---None---None---OMIM:MTHU002522---umls_source:OMIM",
  "update_date": "2023",
  "object": "OMIM:MTHU002522"
}
```
This is because the entry for `OMIM:has_manifestation` is still incorrect in `predicate-remap.yaml`:
https://github.com/RTXteam/RTX-KG2/blob/f1348b3761ac4c60d91b497fface651cf8bba42a/predicate-remap.yaml#L3081-L3083

**Comment by saramsey** [comment] 2023-08-01 23:43
OK, I am hoping that commit 2fb1226 fixes this. Tagging @ecwood and @acevedol so they are aware I am monkeying around with `predicate-remap.yaml`. This is slated for KG2.8.5pre, I suppose.

**Comment by ecwood** [comment] 2023-08-02 20:52
This caused an error in validation:
```
Traceback (most recent call last):
  File "/home/runner/work/RTX-KG2/RTX-KG2/RTX-KG2/validate_predicate_remap_yaml.py", line 195, in <module>
    f"{relation} should map to {allowed_biolink_curies_set} ({mapping_term_used.split('_')[0]})"
AssertionError: OMIM:has_manifestation should map to {'biolink:superclass_of'} (narrow)
```

**Comment by saramsey** [comment] 2023-09-23 02:12
Thank you @ecwood!

I can confirm, this is fixed in KG2.8.4c at least in Neo4j. 

<img width="876" alt="Screenshot 2023-09-22 at 7 11 09 PM" src="https://github.com/RTXteam/RTX-KG2/assets/5562107/fd35410a-7365-4dfd-b5f2-97fc69a51757">

I propose to close it out.  If I've jumped the gun on this @amykglen  please reopen.

**Comment by saramsey** [comment] 2023-09-23 02:12
Big thumbs up for including a Cypher reprex in the issue.

**Closed by saramsey** 2023-09-23 02:12 UTC
Labels: bug, verify this fix in next kg2 build
