### ISSUE TITLE
Get Rid of Automatic Version Update

### ISSUE THREAD

**Issue by acevedol** [RTXteam/RTX-KG2#216] opened 2022-06-10 23:03 UTC
1. Get rid of automatic version update
2. ....

**Comment by ecwood** [comment] 2023-06-27 22:58
While a version of this was done previously (4217b3f, f683898, 1514437 and possibly others), it required a lot of manual intervention that wasn't documented. With [ec79ed1](https://github.com/RTXteam/RTX-KG2/commit/ec79ed1b33daf36a6ce5a868315304704e2e8883) and [d7c5f3a](https://github.com/RTXteam/RTX-KG2/commit/d7c5f3a1dc82c89e51b5e37d7b68d56457507d17), the increment of both the major and the minor version number is done by a user placing a file in the build directory. This method is also documented now.

**Comment by ecwood** [comment] 2023-07-24 23:37
I am closing this issue because this worked as intended in the `KG2.8.4pre` build.

**Closed by ecwood** 2023-07-24 23:37 UTC
Labels: verify this fix in next kg2 build
