### ISSUE TITLE
Is it time to upgrade the KG2pre build system to Ubuntu 22.04?

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX-KG2#262] opened 2023-03-08 20:35 UTC
The KG2pre build system was developed for (and, as emphasized about a dozen places in the documentation, unapologetically and explicitly tied to) Ubuntu 18.04. But Ubuntu 18.04, which came out in April 2018, is now almost five years old. Canonical has set the EOL for support for that release to be April 30, 2023, I think (see [this page](https://computing.cs.cmu.edu/news/2022/eol-ubuntu-1804)). Is it time to make the jump to Ubuntu 22.04?  It might all "just work", and if so, we'd just need to do a cut-and-paste on the documentation and upgrade the OS version in the build instances. Thoughts?

**Comment by saramsey** [comment] 2023-03-08 20:35
Also tagging @amykglen for her thoughts.

**Comment by ecwood** [comment] 2023-06-21 21:12
`kg2erica.rtx.ai` was created with Ubuntu 22.04. `setup-kg2-build.sh` failed on first go. Here's a snippet of the log:

```
Preparing to unpack .../00-libpython3.7-minimal_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking libpython3.7-minimal:amd64 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7-minimal.^M
Preparing to unpack .../01-python3.7-minimal_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking python3.7-minimal (3.7.17-1+jammy1) ...^M
Selecting previously unselected package libexpat1-dev:amd64.^M
Preparing to unpack .../02-libexpat1-dev_2.4.7-1ubuntu0.2_amd64.deb ...^M
Unpacking libexpat1-dev:amd64 (2.4.7-1ubuntu0.2) ...^M
Selecting previously unselected package libpython3.7-stdlib:amd64.^M
Preparing to unpack .../03-libpython3.7-stdlib_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking libpython3.7-stdlib:amd64 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package libpython3.7:amd64.^M
Preparing to unpack .../04-libpython3.7_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking libpython3.7:amd64 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package libpython3.7-dev:amd64.^M
Preparing to unpack .../05-libpython3.7-dev_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking libpython3.7-dev:amd64 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7.^M
Preparing to unpack .../06-python3.7_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking python3.7 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7-dev.^M
Preparing to unpack .../07-python3.7-dev_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking python3.7-dev (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7-lib2to3.^M
Preparing to unpack .../08-python3.7-lib2to3_3.7.17-1+jammy1_all.deb ...^M
Unpacking python3.7-lib2to3 (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7-distutils.^M
Preparing to unpack .../09-python3.7-distutils_3.7.17-1+jammy1_all.deb ...^M
Unpacking python3.7-distutils (3.7.17-1+jammy1) ...^M
Selecting previously unselected package python3.7-venv.^M
Preparing to unpack .../10-python3.7-venv_3.7.17-1+jammy1_amd64.deb ...^M
Unpacking python3.7-venv (3.7.17-1+jammy1) ...^M
Setting up libpython3.7-minimal:amd64 (3.7.17-1+jammy1) ...^M
Setting up libexpat1-dev:amd64 (2.4.7-1ubuntu0.2) ...^M
Setting up python3.7-minimal (3.7.17-1+jammy1) ...^M
Setting up python3.7-lib2to3 (3.7.17-1+jammy1) ...^M
Setting up libpython3.7-stdlib:amd64 (3.7.17-1+jammy1) ...^M
Setting up libpython3.7:amd64 (3.7.17-1+jammy1) ...^M
Setting up libpython3.7-dev:amd64 (3.7.17-1+jammy1) ...^M
Setting up python3.7-distutils (3.7.17-1+jammy1) ...^M
Setting up python3.7 (3.7.17-1+jammy1) ...^M
Setting up python3.7-venv (3.7.17-1+jammy1) ...^M
Setting up python3.7-dev (3.7.17-1+jammy1) ...^M
Processing triggers for man-db (2.10.2-1) ...^M
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...^M
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-distutils all 3.10.6-1~22.04 [139 kB]
Fetched 139 kB in 0s (9465 kB/s)
Unrecognized python3 distutils .deb package filename; this is a bug in setup-python37-with-pip3-in-ubuntu.shinc
```

**Comment by ecwood** [comment] 2023-06-21 21:46
3e1cb8f addressed that issue. New error:
```
Collecting mypy>=0.0
  Downloading mypy-0.902-cp37-cp37m-manylinux2010_x86_64.whl (21.5 MB)
     ━━━━━━━╸                                 4.2/21.5 MB 17.2 MB/s eta 0:00:02
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 420, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 380, in resolve
    success = self._backtrack()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 320, in _backtrack
    success = _patch_criteria()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 309, in _patch_criteria
    if not candidates:
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
    version=version,
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    version=version,
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 542, in _prepare_linked_requirement
    hashes,
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 170, in unpack_url
    hashes=hashes,
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 87, in response_chunks
    decode_content=False,
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/kg2-venv/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python3.7 -m pip install --upgrade pip
```

**Comment by ecwood** [comment] 2023-06-21 22:23
That error didn't happen this time. New error:
```
[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python3.7 -m pip install --upgrade pip
+ curl -s -L -f -H 'Accept: application/zip' https://github.com/RTXteam/robot/releases/download/v1.3.0/robot.jar
+ curl -s https://raw.githubusercontent.com/RTXteam/robot/v1.3.0/bin/robot
+ chmod +x /home/ubuntu/kg2-build/robot
+ curl -s -L -f /home/ubuntu/kg2-build https://github.com/RTXteam/owltools/releases/download/v0.3.0/owltools
+ chmod +x /home/ubuntu/kg2-build/owltools
+ RAPTOR_NAME=raptor2-2.0.15
+ curl -s -L -f -o /home/ubuntu/kg2-build/raptor2-2.0.15.tar.gz http://download.librdf.org/source/raptor2-2.0.15.tar.gz
+ rm -r -f /home/ubuntu/kg2-build/raptor2-2.0.15
+ tar xzf /home/ubuntu/kg2-build/raptor2-2.0.15.tar.gz -C /home/ubuntu/kg2-build
+ cd /home/ubuntu/kg2-build/raptor2-2.0.15
+ ./autogen.sh --prefix=/usr/local
autogen.sh: Looking for programs: automake aclocal autoconf autoheader libtoolize gtkdocize
autogen.sh: automake program 'automake' V 011605 (min 011102) in /usr/bin
autogen.sh: aclocal program 'aclocal' V 011605 (min 011102) in /usr/bin
autogen.sh: autoconf program 'autoconf' V 027100 (min 026200) in /usr/bin
autogen.sh: autoheader program 'autoheader' V 027100 (min 026200) in /usr/bin
autogen.sh: libtoolize program 'libtoolize' V 020406 (min 020200) in /usr/bin
autogen.sh: gtkdocize program 'gtkdocize' V 013301 (min 010300) in /usr/bin
autogen.sh: Dependencies satisfied
 
autogen.sh: Processing directory .
autogen.sh: Running libtoolize --force --copy --automake 
autogen.sh: Running gtkdocize --copy
autogen.sh: Running aclocal -Wall -I build 
autogen.sh: Running autoheader
autogen.sh: Running automake --gnu --add-missing --force --copy -Wall
configure.ac:70: installing 'build/compile'
configure.ac:32: installing 'build/missing'
examples/Makefile.am: installing 'build/depcomp'
parallel-tests: installing 'build/test-driver'
autogen.sh: Running autoconf -Wall
configure.ac:86: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
configure.ac:86: the top level
configure.ac:295: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:295: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:295: the top level
configure.ac:298: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:298: You should run autoupdate.
./lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
configure.ac:298: the top level
 
autogen.sh: Running ./configure --enable-maintainer-mode --enable-gtk-doc --enable-silent-rules --prefix=/usr/local
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether build environment is sane... yes
checking whether make supports the include directive... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking whether gcc is clang... checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) no
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking for library containing yywrap... -ll
checking whether yytext is a pointer... yes
checking flex... 2.6.4 - OK
checking for bison3... no
checking for bison... bison
checking for GNU bison... 3.8.2 - OK
checking for gnutar... no
checking for gtar... no
checking for tar... tar
checking for perl... perl
checking for jing... no
checking for echo... echo
checking for supported gcc warning flags... 
checking whether gcc supports -Wall... yes
checking whether gcc supports -Wc++-compat... yes
checking whether gcc supports -Wextra... yes
checking whether gcc supports -Wunused... yes
checking whether gcc supports -Waggregate-return... yes
checking whether gcc supports -Wbad-function-cast... yes
checking whether gcc supports -Wcast-align... yes
checking whether gcc supports -Wdeclaration-after-statement... yes
checking whether gcc supports -Wdisabled-optimization... yes
checking whether gcc supports -Wdiv-by-zero... yes
checking whether gcc supports -Wendif-labels... yes
checking whether gcc supports -Werror-implicit-function-declaration... yes
checking whether gcc supports -Wfloat-equal... yes
checking whether gcc supports -Wformat-security... yes
checking whether gcc supports -Wframe-larger-than=4096... yes
checking whether gcc supports -Winit-self... yes
checking whether gcc supports -Winline... yes
checking whether gcc supports -Wmissing-declarations... yes
checking whether gcc supports -Wmissing-format-attribute... yes
checking whether gcc supports -Wmissing-noreturn... yes
checking whether gcc supports -Wmissing-prototypes... yes
checking whether gcc supports -Wnested-externs... yes
checking whether gcc supports -Wold-style-definition... yes
checking whether gcc supports -Wpacked... yes
checking whether gcc supports -Wpointer-arith... yes
checking whether gcc supports -Wredundant-decls... yes
checking whether gcc supports -Wshadow... yes
checking whether gcc supports -Wsign-compare... yes
checking whether gcc supports -Wstrict-prototypes... yes
checking whether gcc supports -Wswitch-enum... yes
checking whether gcc supports -Wundef... yes
checking whether gcc supports -Wunreachable-code... yes
checking whether gcc supports -Wunsafe-loop-optimizations... yes
checking whether gcc supports -Wwrite-strings... yes
checking whether gcc supports -Wshorten-64-to-32... no
checking whether gcc supports -Wno-conversion... yes
checking whether gcc supports -Wno-format-nonliteral... yes
checking whether gcc supports -Wno-missing-field-initializers... yes
checking whether gcc supports -Wno-sign-conversion... yes
checking whether gcc supports -Wno-system-headers... yes
checking whether gcc supports -Wno-unused-parameter... yes
checking whether gcc supports -Wswitch-bool... yes
checking whether gcc supports -Wlogical-not-parentheses... yes
checking whether gcc supports -Wsizeof-array-argument... yes
checking whether gcc supports -Wbool-compare... yes
checking whether gcc supports -Wc90-c99-compat... yes
checking whether gcc supports -Wc99-c11-compat... yes
checking gcc supports warning flags...  -Wall -Wc++-compat -Wextra -Wunused -Waggregate-return -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wdiv-by-zero -Wendif-labels -Werror-implicit-function-declaration -Wfloat-equal -Wformat-security -Wframe-larger-than=4096 -Winit-self -Winline -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wsign-compare -Wstrict-prototypes -Wswitch-enum -Wundef -Wunreachable-code -Wunsafe-loop-optimizations -Wwrite-strings -Wno-conversion -Wno-format-nonliteral -Wno-missing-field-initializers -Wno-sign-conversion -Wno-system-headers -Wno-unused-parameter -Wswitch-bool -Wlogical-not-parentheses -Wsizeof-array-argument -Wbool-compare -Wc90-c99-compat -Wc99-c11-compat
checking for egrep... (cached) /usr/bin/grep -E
checking for errno.h... yes
checking for fcntl.h... yes
checking for stdlib.h... (cached) yes
checking for stddef.h... yes
checking for unistd.h... (cached) yes
checking for string.h... (cached) yes
checking for limits.h... yes
checking for math.h... yes
checking for getopt.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/param.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for setjmp.h... yes
checking for stat... yes
checking for fetch.h... no
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... no
checking for inline... inline
checking whether __FUNCTION__ is available... yes
checking for gettimeofday... yes
checking for getopt... yes
checking for getopt_long... yes
checking for stricmp... no
checking for strcasecmp... yes
checking for vsnprintf... yes
checking for isascii... yes
checking for setjmp... yes
checking for strtok_r... yes
checking for qsort_r... yes
checking for qsort_s... no
checking for vasprintf... yes
checking whether need to declare optind... no
checking whether vsnprintf has C99 compatible return value... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for xml2-config... xml2-config
checking for xmlCreatePushParserCtxt... yes
checking for libxml via xml2-config... yes - 2.9.13
checking for xslt-config... no
checking for curl-config... no
checking for LIBCURL... no
checking for libcurl via pkg-config... no - not found
checking for ICU... no
checking for xmlCreatePushParserCtxt... (cached) yes
checking libxml library... yes - version 2.9.13
checking for libxml/nanohttp.h... yes
checking for libxml/parser.h... yes
checking for libxml/hash.h... yes
checking for libxml/SAX2.h... yes
checking if libxml xmlEntity has name_length field... no
checking if libxml xmlEntity has etype field... yes
checking if libxml xmlSAXHandler has initialized field... yes
checking if libxml xmlSAXHandler has externalSubset field... yes
checking for xmlSAX2InternalSubset... yes
checking for xmlCtxtUseOptions... yes
checking if libxml has parser option XML_PARSE_NONET... yes
checking for libxml/HTMLparser.h... yes
checking if libxml has parser option HTML_PARSE_NONET... yes
checking for yajl installation... not found. Get it from http://lloyd.github.com/yajl/ and use --with-yajl=DIR if necessary to configure the installation directory.
checking GRDDL parser requirements... no - libxml2 and libxslt are both not available
checking JSON parser requirements... no - libyajl is not available
checking RDF parsers required... all
checking RDF serializers required... all
checking XML names version... 1.0
checking WWW libraries available...  libxml 2.9.13
checking WWW library to use... libxml 2.9.13 via xml2-config
checking NFC library to use... none
checking for libinn.h... no
checking date parsing source... raptor parsedate
checking using memory signing... no
checking whether make supports nested variables... (cached) no
checking for gtk-doc... yes
checking for gtkdoc-check... gtkdoc-check.test
checking for gtkdoc-check... /usr/bin/gtkdoc-check
checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... yes
checking for GTKDOC_DEPS... no
checking that generated files are newer than configure... done
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating raptor2.spec
config.status: creating raptor2.rdf
config.status: creating data/Makefile
config.status: creating docs/Makefile
config.status: creating docs/version.xml
config.status: creating examples/Makefile
config.status: creating scripts/Makefile
config.status: creating src/raptor2.h
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating tests/feeds/Makefile
config.status: creating tests/grddl/Makefile
config.status: creating tests/ntriples/Makefile
config.status: creating tests/ntriples-2013/Makefile
config.status: creating tests/nquads-2013/Makefile
config.status: creating tests/rdfa/Makefile
config.status: creating tests/rdfa11/Makefile
config.status: creating tests/json/Makefile
config.status: creating tests/rdfxml/Makefile
config.status: creating tests/turtle/Makefile
config.status: creating tests/turtle-2013/Makefile
config.status: creating tests/trig/Makefile
config.status: creating utils/Makefile
config.status: creating librdfa/Makefile
config.status: creating raptor2.pc
config.status: creating src/raptor_config.h
config.status: executing depfiles commands
config.status: error: in `/home/ubuntu/kg2-build/raptor2-2.0.15':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```

**Comment by ecwood** [comment] 2023-06-21 23:00
That error was solved by installing `make`. It must no longer come installed. New error: (note it doesn't error out but this doesn't seem good)

```
+ sudo -u postgres psql -c 'DO $do$ BEGIN IF NOT EXISTS ( SELECT FROM pg_catalog.pg_roles WHERE rolname = '\''ubuntu'\'' ) THEN CREATE ROLE ubuntu LOGIN PASSWORD null; END IF; END $do$;'
could not change directory to "/home/ubuntu/kg2-build/raptor2-2.0.16": Permission denied
DO
+ sudo -u postgres psql -c 'ALTER USER ubuntu WITH password null'
could not change directory to "/home/ubuntu/kg2-build/raptor2-2.0.16": Permission denied
ALTER ROLE
```

**Comment by ecwood** [comment] 2023-06-21 23:42
Here are the types of errors in DrugCentral's extract caused by problems with how postgres is installed:

```
ERROR:  syntax error at or near "LAMIVUDINE"
LINE 1: LAMIVUDINE TRIUMEQ PD VIIV HLTHCARE EQ 60MG BASE;
        ^
ERROR:  syntax error at or near "EQ"
LINE 1: EQ 5MG BASE;
        ^
ERROR:  trailing junk after numeric literal at or near "30M"
LINE 1: 30MG N 215413  2022-03-30 1 RX VIIV HEALTHCARE CO TABLET, FO...
        ^
ERROR:  syntax error at or near "DOLUTEGRAVIR"
LINE 1: DOLUTEGRAVIR SODIUM;
        ^
ERROR:  syntax error at or near "LAMIVUDINE"
LINE 1: LAMIVUDINE TRIUMEQ PD VIIV HLTHCARE EQ 60MG BASE;
        ^
ERROR:  syntax error at or near "EQ"
LINE 1: EQ 5MG BASE;
        ^
ERROR:  trailing junk after numeric literal at or near "30M"
LINE 1: 30MG N 215413  2022-03-30 1 RX VIIV HEALTHCARE CO TABLET, FO...
        ^
ERROR:  syntax error at or near "TADALAFIL"
LINE 1: TADALAFIL ENTADFI VERU 5MG;
        ^
ERROR:  trailing junk after numeric literal at or near "5M"
LINE 1: 5MG N 215423  2021-12-09 1 RX VERU INC CAPSULE ORAL 001
        ^
ERROR:  syntax error at or near "TADALAFIL"
LINE 1: TADALAFIL ENTADFI VERU 5MG;
        ^
ERROR:  trailing junk after numeric literal at or near "5M"
LINE 1: 5MG N 215423  2021-12-09 1 RX VERU INC CAPSULE ORAL 001
```
and
```
ERROR:  must be owner of schema public
ERROR:  permission denied for database drugcentral
ERROR:  must be owner of schema public
SET
SET
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.act_table_full (
                     ^
ERROR:  relation "public.act_table_full" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.action_type (
                     ^
ERROR:  relation "public.action_type" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.action_type_id_seq" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.active_ingredient (
                     ^
ERROR:  relation "public.active_ingredient" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.active_ingredient_id_seq" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.approval (
                     ^
ERROR:  relation "public.approval" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.approval_id_seq" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.approval_type (
                     ^
ERROR:  relation "public.approval_type" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.approval_type_id_seq" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.atc (
                     ^
ERROR:  relation "public.atc" does not exist
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE public.atc_ddd (
                     ^
ERROR:  relation "public.atc_ddd" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.atc_ddd_id_seq" does not exist
ERROR:  permission denied for schema public
ERROR:  relation "public.atc_id_seq" does not exist
```

**Comment by ecwood** [comment] 2023-06-27 17:13
The issue with `extract-drugcentral.sh` has been resolved. It does not appear the problem was with Ubuntu 22.04.

**Comment by ecwood** [comment] 2023-07-24 23:38
I am closing this issue because this worked as intended in the `KG2.8.4pre` build.

**Closed by ecwood** 2023-07-24 23:38 UTC
Labels: verify this fix in next kg2 build, Erica-look
